// @ts-check
/// <reference types="@actions/github-script" />

/**
 * Generates a standalone workflow-id XML comment marker for searchability.
 * This marker enables finding all items (issues, discussions, PRs, comments)
 * generated by a specific workflow.
 *
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Standalone workflow-id XML comment marker
 */
function generateWorkflowIdMarker(workflowId) {
  return `<!-- gh-aw-workflow-id: ${workflowId} -->`;
}

/**
 * Gets the workflow-id marker content (without XML comment wrapper) for searching.
 * This is used when searching for issues/discussions/PRs by workflow-id.
 *
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Workflow-id marker content for search queries
 */
function getWorkflowIdMarkerContent(workflowId) {
  return `gh-aw-workflow-id: ${workflowId}`;
}

/**
 * Generates an XML comment marker with agentic workflow metadata for traceability.
 * This marker enables searching and tracing back items generated by an agentic workflow.
 *
 * Note: This function is duplicated in messages_footer.cjs. While normally we would
 * consolidate to a shared module, importing messages_footer.cjs here would cause the
 * bundler to inline messages_core.cjs which contains 'GH_AW_SAFE_OUTPUT_MESSAGES:' in
 * a warning message, breaking tests that check for env var declarations.
 *
 * @param {string} workflowName - Name of the workflow
 * @param {string} runUrl - URL of the workflow run
 * @returns {string} XML comment marker with workflow metadata
 */
function generateXMLMarker(workflowName, runUrl) {
  // Read engine metadata from environment variables
  const engineId = process.env.GH_AW_ENGINE_ID || "";
  const engineVersion = process.env.GH_AW_ENGINE_VERSION || "";
  const engineModel = process.env.GH_AW_ENGINE_MODEL || "";
  const trackerId = process.env.GH_AW_TRACKER_ID || "";
  const runId = process.env.GITHUB_RUN_ID || "";
  const workflowId = process.env.GH_AW_WORKFLOW_ID || "";

  // Build the key-value pairs for the marker
  const parts = [];

  // Always include agentic-workflow name
  parts.push(`gh-aw-agentic-workflow: ${workflowName}`);

  // Add tracker-id if available (for searchability and tracing)
  if (trackerId) {
    parts.push(`gh-aw-tracker-id: ${trackerId}`);
  }

  // Add engine ID if available
  if (engineId) {
    parts.push(`engine: ${engineId}`);
  }

  // Add version if available
  if (engineVersion) {
    parts.push(`version: ${engineVersion}`);
  }

  // Add model if available
  if (engineModel) {
    parts.push(`model: ${engineModel}`);
  }

  // Add numeric run ID if available
  if (runId) {
    parts.push(`id: ${runId}`);
  }

  // Add workflow identifier if available
  if (workflowId) {
    parts.push(`workflow_id: ${workflowId}`);
  }

  // Always include run URL
  parts.push(`run: ${runUrl}`);

  // Return the XML comment marker
  return `<!-- ${parts.join(", ")} -->`;
}

/**
 * Generate footer for expired entity closing comments
 * @param {string} workflowName - Name of the workflow
 * @param {string} runUrl - URL of the workflow run
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Footer text with workflow run link and XML markers
 */
function generateExpiredEntityFooter(workflowName, runUrl, workflowId) {
  let footer = `\n\n> Closed by [${workflowName}](${runUrl})`;

  // Add XML markers for searchability
  footer += "\n\n<!-- gh-aw-expired-comments -->";
  if (workflowId) {
    footer += "\n" + generateWorkflowIdMarker(workflowId);
  }
  footer += "\n" + generateXMLMarker(workflowName, runUrl);

  return footer;
}

/**
 * Generates a standalone workflow-call-id XML comment marker for close-older-issues
 * disambiguation. This marker contains the calling workflow's runtime identity
 * ("owner/repo/workflow-id") and is used to distinguish multiple callers that share
 * the same reusable workflow (and therefore the same `gh-aw-workflow-id`).
 *
 * @param {string} callerWorkflowId - Calling workflow identifier (e.g. "owner/repo/workflow-id")
 * @returns {string} Standalone workflow-call-id XML comment marker
 */
function generateWorkflowCallIdMarker(callerWorkflowId) {
  return `<!-- gh-aw-workflow-call-id: ${callerWorkflowId} -->`;
}

/**
 * Normalizes a user-supplied close-older-key to identifier style.
 * Converts to lowercase, replaces runs of non-alphanumeric/dash/underscore characters
 * with a single dash, then trims leading and trailing dashes and underscores.
 *
 * Examples: "My Key!" → "my-key", "  hello world  " → "hello-world"
 *
 * @param {string} key - Raw user-supplied key
 * @returns {string} Normalized identifier-style key, or empty string if nothing remains
 */
function normalizeCloseOlderKey(key) {
  return key
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "");
}

/**
 * Generates a standalone close-key XML comment marker for close-older matching.
 * When a user provides an explicit `close-older-key`, this marker is embedded in
 * the issue/discussion body and used as the primary deduplication key instead of
 * the workflow-id or workflow-call-id markers.
 *
 * @param {string} closeKey - Normalized close-older deduplication key
 * @returns {string} Standalone close-key XML comment marker
 */
function generateCloseKeyMarker(closeKey) {
  return `<!-- gh-aw-close-key: ${closeKey} -->`;
}

/**
 * Gets the close-key marker content (without XML comment wrapper) for searching.
 * This is used when searching for issues/discussions by close-older-key.
 *
 * @param {string} closeKey - Normalized close-older deduplication key
 * @returns {string} Close-key marker content for search queries
 */
function getCloseKeyMarkerContent(closeKey) {
  return `gh-aw-close-key: ${closeKey}`;
}

module.exports = {
  generateXMLMarker,
  generateWorkflowIdMarker,
  generateWorkflowCallIdMarker,
  getWorkflowIdMarkerContent,
  generateExpiredEntityFooter,
  normalizeCloseOlderKey,
  generateCloseKeyMarker,
  getCloseKeyMarkerContent,
};
